# Generated by Django 4.1.7 on 2023-05-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emplooyes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.TextField(max_length=40)),
                ('Mobile', models.DecimalField(decimal_places=11, max_digits=11)),
            ],
        ),
    ]
