# Generated by Django 4.1.7 on 2023-05-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.TextField(max_length=40)),
                ('Password', models.TextField(max_length=60)),
                ('Type', models.BooleanField()),
            ],
        ),
    ]
