# Generated by Django 4.1.7 on 2023-05-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_xusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplooyes',
            name='id',
        ),
        migrations.AddField(
            model_name='emplooyes',
            name='Address',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='emplooyes',
            name='AviVacdays',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='emplooyes',
            name='Birthdate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='emplooyes',
            name='Department',
            field=models.TextField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='emplooyes',
            name='Eamil',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='emplooyes',
            name='Gender',
            field=models.TextField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='emplooyes',
            name='Mstatue',
            field=models.TextField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='emplooyes',
            name='Salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emplooyes',
            name='Mobile',
            field=models.DecimalField(decimal_places=11, default=0.0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='emplooyes',
            name='Username',
            field=models.TextField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='emplooyes',
            name='Id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
