# Generated by Django 4.1.7 on 2023-05-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_emplooyes_mobile_alter_emplooyes_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplooyes',
            name='Mobile',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='emplooyes',
            name='Salary',
            field=models.IntegerField(default=1),
        ),
    ]
