# Generated by Django 4.1.7 on 2023-05-31 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_emplooyes_mobile_alter_emplooyes_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplooyes',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='emplooyes',
            name='Salary',
        ),
    ]
