# Generated by Django 4.1.7 on 2023-05-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_emplooyes_mobile_remove_emplooyes_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplooyes',
            name='AviVacdays',
        ),
        migrations.AlterField(
            model_name='emplooyes',
            name='Address',
            field=models.TextField(default=None, max_length=40),
        ),
    ]
