# Generated by Django 4.1.7 on 2023-05-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_emplooyes_avivacdays_alter_emplooyes_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplooye',
            fields=[
                ('Id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('Username', models.TextField(default=None, max_length=40)),
                ('Address', models.TextField(default=None, max_length=40)),
                ('Eamil', models.TextField(default=None, max_length=100)),
                ('Birthdate', models.DateField(default=None)),
                ('Department', models.TextField(default=None, max_length=40)),
                ('Gender', models.TextField(default=None, max_length=40)),
                ('Mstatue', models.TextField(default=None, max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Emplooyes',
        ),
    ]
