# Generated by Django 4.1.7 on 2023-05-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_emplooye_delete_emplooyes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplooyes',
            fields=[
                ('Id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('Username', models.TextField(default=None, max_length=40)),
                ('XAddress', models.TextField(default=None, max_length=50)),
                ('Eamil', models.TextField(default=None, max_length=100)),
                ('Birthdate', models.DateField(default=None)),
                ('Department', models.TextField(default=None, max_length=40)),
                ('Gender', models.TextField(default=None, max_length=40)),
                ('Mstatue', models.TextField(default=None, max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Emplooye',
        ),
    ]
