# Generated by Django 4.1.7 on 2023-05-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_emplooyes_delete_emplooye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplooyes',
            name='XAddress',
        ),
        migrations.AddField(
            model_name='emplooyes',
            name='Address',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='emplooyes',
            name='AviVacdays',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='emplooyes',
            name='Mobile',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='emplooyes',
            name='Salary',
            field=models.DecimalField(decimal_places=5, default=1.0, max_digits=10),
        ),
    ]
