# Generated by Django 4.1.7 on 2023-05-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_emplooyes_xaddress_emplooyes_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplooyes',
            name='Salary',
            field=models.DecimalField(decimal_places=5, default='1.0', max_digits=10),
        ),
    ]
