# Generated by Django 4.1.7 on 2023-05-31 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_emplooyes_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emplooyes',
            old_name='Eamil',
            new_name='Email',
        ),
    ]
