# Generated by Django 4.1.7 on 2023-05-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_emplooyes_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplooyes',
            name='Username',
            field=models.TextField(default='None', max_length=40),
        ),
    ]
