# Generated by Django 4.1.7 on 2023-06-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_emplooyes_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRs',
            fields=[
                ('Id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('Username', models.TextField(default='None', null=True)),
                ('Password', models.TextField(default='None', null=True)),
                ('Mobile', models.IntegerField(default=10, null=True)),
                ('Address', models.TextField(default='None', null=True)),
                ('Email', models.TextField(default='None', null=True)),
                ('Birthdate', models.DateField(null=True)),
                ('Salary', models.IntegerField(default=1000, null=True)),
                ('Department', models.TextField(default='HR', null=True)),
                ('Gender', models.TextField(default='Male', null=True)),
                ('Mstatue', models.TextField(default='Single', null=True)),
                ('AviVacdays', models.IntegerField(default=5, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emplooyes',
            name='Address',
            field=models.TextField(default='None', null=True),
        ),
        migrations.AlterField(
            model_name='emplooyes',
            name='AviVacdays',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='emplooyes',
            name='Birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='emplooyes',
            name='Department',
            field=models.TextField(default='Genral', null=True),
        ),
        migrations.AlterField(
            model_name='emplooyes',
            name='Email',
            field=models.TextField(default='None', null=True),
        ),
        migrations.AlterField(
            model_name='emplooyes',
            name='Gender',
            field=models.TextField(default='Male', null=True),
        ),
        migrations.AlterField(
            model_name='emplooyes',
            name='Mobile',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='emplooyes',
            name='Mstatue',
            field=models.TextField(default='Single', null=True),
        ),
        migrations.AlterField(
            model_name='emplooyes',
            name='Salary',
            field=models.IntegerField(default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='emplooyes',
            name='Username',
            field=models.TextField(default='None', null=True),
        ),
    ]
