# Generated by Django 4.1.7 on 2023-06-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_hrs_alter_emplooyes_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplooyes',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hrs',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
