# Generated by Django 4.1.7 on 2023-06-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_emplooyes_id_alter_hrs_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VactionId', models.IntegerField(default=0)),
                ('EmplooyeUsername', models.TextField(default='none')),
                ('EmplooyeDepartment', models.TextField(default='none')),
                ('Startdate', models.DateField()),
                ('Enddate', models.DateField()),
                ('Reason', models.TextField(default='Personal Reasons', null=True)),
                ('Statues', models.TextField(default='Panding')),
            ],
        ),
    ]
