# Generated by Django 4.1.7 on 2023-06-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_vactions'),
    ]

    operations = [
        
    ]
