# Generated by Django 4.1.7 on 2023-06-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_remove_vactions_vactionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vactions',
            old_name='EmplooyeDepartment',
            new_name='EmployeeDepartment',
        ),
        migrations.RenameField(
            model_name='vactions',
            old_name='EmplooyeUsername',
            new_name='EmployeeUsername',
        ),
    ]
